#!/usr/bin/env bash
# build_catalog.sh — regenerate the OS Catalog: a one-line index of everything we own.
# Read by /scout's FILES pass FIRST. Run after adding a tool/command/agent/memory.
# Pattern: Karpathy LLM-Wiki index.md (see core/CLAUDE.md). Auto-generated — do not hand-edit CATALOG.md.
set -uo pipefail
ROOT="${1:-/config/workspace}"
MEM="/config/.claude/projects/-config-workspace/memory"
OUT="$ROOT/CATALOG.md"

desc() { awk -F': ' '/^description:/{ $1=""; sub(/^ /,""); print; exit }' "$1" 2>/dev/null; }

{
  echo "# CATALOG — what the OS owns"
  echo
  echo "> Auto-generated by \`core/tools/catalog/build_catalog.sh\`. **\`/scout\` reads this FIRST** for the FILES pass. Regenerate after adding a tool/command/agent/memory — do NOT hand-edit."
  echo

  echo "## Commands — \`.claude/commands/\` (invoke with \`/name\`)"
  for f in "$ROOT"/.claude/commands/*.md; do [ -e "$f" ] || continue
    echo "- **/$(basename "$f" .md)** — $(desc "$f")"; done
  echo

  echo "## Sub-agents — \`.claude/agents/\`"
  for f in "$ROOT"/.claude/agents/*.md; do [ -e "$f" ] || continue
    echo "- **$(basename "$f" .md)** — $(desc "$f")"; done
  echo

  echo "## Tools — \`core/tools/\`"
  for d in "$ROOT"/core/tools/*/; do [ -d "$d" ] || continue
    n=$(basename "$d")
    line=$(grep -m1 -hE '^[A-Za-z]' "$d"README.md 2>/dev/null)
    [ -z "$line" ] && line=$(grep -hE '^(#|//) ' "$d"*.py "$d"*.sh "$d"*.ts "$d"*.mjs 2>/dev/null | grep -vE '^#!' | head -1 | sed -E 's#^[#/]+[[:space:]]*##')
    echo "- **$n** — ${line:-script}"; done
  echo

  echo "## Memory wiki — \`$MEM/MEMORY.md\`"
  grep -E '^- ' "$MEM/MEMORY.md" 2>/dev/null || echo "- (see MEMORY.md)"
  echo

  echo "## Projects / workloads (each = its own backed-up repo)"
  for p in operations core autotube; do [ -d "$ROOT/$p" ] || continue
    rem=$(git -C "$ROOT/$p" remote get-url origin 2>/dev/null || echo "no remote")
    echo "- **$p/** — $rem"; done
  echo

  echo "## Connected services (key NAMES only — values in \`operations/.secrets/.env\`)"
  printf -- "- "; grep -oE '^[A-Z][A-Z0-9_]+=' "$ROOT/operations/.secrets/.env" 2>/dev/null | sed 's/=//' | sort -u | paste -sd' ' -
  echo

  echo "## Infrastructure"
  echo "- Full map: \`operations/INFRASTRUCTURE.md\` · Production VPS: Main \`187.124.233.122\`"
} > "$OUT"
echo "wrote $OUT ($(wc -l < "$OUT") lines)"
